collections:
  authors:
    output: true

highlighter: pygments

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
    

plugins:
  - "kramdown-plantuml"


